In [4]:
import numpy as np

In [5]:
arr = [6, 7, 8, 9]
print(type(arr))


<class 'list'>


In [6]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape)
print(a.dtype) 
print(a.ndim)

(4,)
int32
1


In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [13]:
np.random.random((2, 3))

array([[0.39310196, 0.6811029 , 0.14844665],
       [0.61817822, 0.8652894 , 0.66034616]])

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
d = np.array(np.random.randn(2,3))
d

array([[ 0.60352   , -2.63364378, -1.18294266],
       [ 2.3382269 , -0.87621157, -0.83768039]])

In [34]:
d[1, 0:2] # Row of index one, Columns from index 0 to 2-1

array([ 2.3382269 , -0.87621157])

In [33]:
d[:2, :2] # Up to row index 2-1, up to column index 2-1

array([[ 0.60352   , -2.63364378],
       [ 2.3382269 , -0.87621157]])