# 1st Live Session Class 21/09/23

In [1]:
import numpy as np

In [7]:
# Simple numpy array
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [12]:
# Array shapes describe the dimensions (order of rows and columns)
a.shape

(4,)

In [10]:
# A 0 dimension array as there is only one number
b = np.array(42)
b.shape

()

In [16]:
# Multi-dimensional array e.g 2-D, 3-D etc.
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [26]:
# Indexes to access array elements
a[2], b, c[1][0] #B has no dimensions so we can't index it. It's basically a single valued variable 

(3, array(42), 4)

In [30]:
# We can also reshape numpy arrays to assume a different dimensional shape
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
d.shape

(9,)

In [32]:
d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# When reshaping, you must make sure the numbers of values can fit into the array
d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
# Accessing random numbers from the numpy library

np.random.rand() #Random array from a uniform distribution

0.4190398255347094

In [46]:
np.random.randint(13) #Specify the max value in the parentheses

1

In [42]:
np.random.randn(3, 4, 5) #Random array from a normal distribution

array([[[-1.23445460e+00,  6.58938392e-02, -2.25021403e-01,
          1.28841039e+00, -1.72758883e-02],
        [ 3.97931597e-02, -1.41881998e+00,  5.67642457e-01,
         -1.02780202e+00, -6.41638557e-02],
        [ 2.17524101e+00, -3.94035033e-01,  1.93059526e-01,
          1.07214283e-01, -2.74723579e-01],
        [-6.06390788e-02,  4.91723252e-01, -9.45328425e-01,
         -1.31388168e+00, -1.78867898e+00]],

       [[ 8.99235002e-01, -6.34671842e-01,  3.65013889e-02,
          9.69051264e-01, -1.55805659e+00],
        [ 7.34266469e-01,  1.55790314e+00, -1.26181397e+00,
          1.62769966e+00,  8.22805782e-01],
        [-9.78005319e-02,  1.06887689e+00, -3.41076397e-01,
          1.64201538e-01, -6.01406909e-02],
        [ 9.32154327e-01,  3.53298761e-01,  1.81813910e+00,
          1.08578494e+00, -1.85427621e+00]],

       [[-8.22786861e-02, -1.05927457e+00, -3.83591808e-01,
         -9.89931210e-02,  1.49454333e+00],
        [ 4.05743805e-01, -3.97884779e-01,  1.08408429e+00,


In [47]:
# A binomial distribution
np.random.binomial(n=10, p=0.5, size=10) # 10 values with a max value of 10 and a random probability of 0.5

array([6, 5, 4, 6, 4, 5, 4, 6, 5, 4])

In [48]:
# A normal distribution
np.random.normal(loc=2, scale=4, size=10) #Info provided in docstring

array([ 5.18857301,  1.26272867,  0.63025505, -1.54514543, -4.94591415,
        2.17583945, -3.16550055,  4.24454952, -3.31764929,  5.62371735])

In [50]:
# Numpy mean function
np.mean()

In [70]:
e = np.random.randint(4, size=9)
f = np.random.randint(7, size=9)
e,f

(array([1, 3, 0, 2, 3, 1, 2, 3, 2]), array([6, 3, 6, 6, 0, 2, 4, 5, 5]))

In [71]:
np.multiply(e,f)

array([ 6,  9,  0, 12,  0,  2,  8, 15, 10])

In [72]:
e*f

array([ 6,  9,  0, 12,  0,  2,  8, 15, 10])

In [73]:
f * 24

array([144,  72, 144, 144,   0,  48,  96, 120, 120])